### ISSUE TITLE
Dataset-TWSI-2-GOLD.csv.gz and Dataset-TWSI-2.csv have different number of examples

### ISSUE THREAD

**Issue by nvanva** [tudarmstadt-lt/context-eval#4]
data/Dataset-TWSI-2-GOLD.csv.gz has more examples than data/Dataset-TWSI-2.csv which should be processed by WSD systems. This probably means that it is impossible to get 100% coverage.

**Comment by alexanderpanchenko** [comment]
These were some duplicates: 

```
alex@MacBook-Pro-4:~/work/joint/eval/contextualization-eval/data$ sort Dataset-TWSI-2-GOLD.csv | uniq > u
alex@MacBook-Pro-4:~/work/joint/eval/contextualization-eval/data$ wc -l u
  145141 u
```

fixed it
